### ISSUE TITLE
[Insight] Sensitive data should not be present in non-parameter configuration files - in phinx.yml, line 12

### ISSUE THREAD

**Issue by chrl** [chrl/buktopuha#2]
**[in phinx.yml, line 12](https://github.com/chrl/buktopuha/blob/12e0d48f37c093905c950c1849987de2514aeeb3/phinx.yml#L12)**

> A sensitive data has been detected in your configuration file (`user` parameter). You should consider storing it in a single parameter file.

```
    default_database: development
    production:
        adapter: mysql
        host: localhost
        name: production_db
        user: root
        pass: ''
        port: 3306
        charset: utf8

    development:
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/5019e5c2-3cf9-476d-9185-235e6ff23ac0/analyses/1)_
